### ISSUE TITLE
Fill submit page style

### ISSUE THREAD

**Issue by aquarhead** [mashiro-no-rabo/jg#13]
- total file size
- payment button
- overall styles

**Comment by aquarhead** [comment]
Also phone number for contact.

**Comment by aquarhead** [comment]
联系客服按钮 (邮件 / 电话)

**Comment by xhacker** [comment]
你用 static table view 呗……

**Comment by aquarhead** [comment]
擦 好像行哈。。

**Comment by aquarhead** [comment]
只能在 TableViewController 里面用 Static TableView......... fuck
