### ISSUE TITLE
Keep layout when canceling photo

### ISSUE THREAD

**Issue by xhacker** [mashiro-no-rabo/jg#15]
现在有时候撤销图片的时候上面布局会变化。

**Comment by aquarhead** [comment]
求重现?

On 11 February 2014 05:31, xhacker notifications@github.com wrote:

> 现在有时候撤销图片的时候上面布局会变化。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/AquarHEAD/JikanGachou/issues/15
> .

## 

## 楼洵(AquarHEAD)

Blossoms which were the joys that fell,
And leaves, the hopes that yet remain.

## Learn, Code, Debug and Share.

http://about.AquarHEAD.me

**Comment by aquarhead** [comment]
现阶段就这么设计...
