### ISSUE TITLE
Image picker

### ISSUE THREAD

**Issue by xhacker** [mashiro-no-rabo/jg#2]

**Comment by aquarhead** [comment]
1. ~~PoolView 裏面圖片需要能看出橫/豎~~
2. ~~Pool 裏面沒圖片的時候加一段提示文字?~~

**Comment by aquarhead** [comment]
1. ~~修正已選中照片切換相冊後的 bug~~
2. ~~修正打開相冊時的閃爍問題~~

**Comment by aquarhead** [comment]
- [x] 超过40张后禁止再选
- [x] 超过20张后才能点下一步
