### ISSUE TITLE
Progressive submitPage

### ISSUE THREAD

**Issue by aquarhead** [mashiro-no-rabo/jg#24]

**Comment by aquarhead** [comment]
or a status page.

**Comment by aquarhead** [comment]
maybe we could use a little icon in left navi item to show the status?

e.g. a credit card to indicate :topay
a car indicate :shipping etc.

**Comment by xhacker** [comment]
I'll think about this...Too busy these days><

**Comment by aquarhead** [comment]
@xhacker np, you just do #10 now, rest is fine for now~ :D

**Comment by xhacker** [comment]
Okay~What's the plan? When to beta? Final?

**Comment by aquarhead** [comment]
https://github.com/jverdi/JVFloatLabeledTextField

**Comment by aquarhead** [comment]
https://github.com/benzguo/BZGFormField

**Comment by aquarhead** [comment]
![submitpage](https://f.cloud.github.com/assets/222272/2257993/3d0648e2-9e22-11e3-804b-25f377d5f617.jpeg)
