### ISSUE TITLE
Icons for book status

### ISSUE THREAD

**Issue by aquarhead** [mashiro-no-rabo/jg#36]
in GlyphishPro3
- topay: 192-credit-card
- toupload: 234, 266
- toprint: 96, 185
- shipping: 245
- recved: 117

@xhacker your opinion?

**Comment by xhacker** [comment]
- to pay: 192
- to upload: 56
- to print: 185
- shipping: 245
- received: extras-19

**Comment by aquarhead** [comment]
Totally agree!

我就想找个56那效果的没找到><......

**Comment by xhacker** [comment]
hahaha~
